SHOW DATABASES;
CREATE DATABASE LAND;


#CREATING DATABASES WITH PRIMARY KEYS AND FOREIGN KEYS: DO IT YOURSELF CHAPTER 2
CREATE DATABASE ATHLETIC;
USE ATHLETIC;

CREATE TABLE SPORT
(
SPORT_ID   INT,
SPORT_NAME  VARCHAR(50),
PRIMARY KEY (SPORT_ID));

USE ATHLETIC;
CREATE TABLE PLAYER
(PLAYER_ID  INT,
PLAYER_NAME VARCHAR(50),
PLAYER_AGE  INT,
SPORT_ID    INT,
PRIMARY KEY (PLAYER_ID),
FOREIGN KEY (SPORT_ID) REFERENCES SPORT(SPORT_ID));
###########



USE LAND;
CREATE TABLE CONTINENT(
    CONTINENT_ID    INT,
    CONTINENT_NAME  VARCHAR(20),
    POPULATION  BIGINT
);


#INSERT DATA INTO THE CONTINENT TABLE#
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME, POPULATION) VALUES (1, 'ASIA', 4641054775);
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME, POPULATION) VALUES (2, 'AFRICA', 1340598147);
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME, POPULATION) VALUES (3, 'EUROPE', 747636026);
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME, POPULATION) VALUES (4, 'NORTH AMERICA', 592072212);
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME, POPULATION) VALUES (5, 'SOUTH AMERICA', 430759766);
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME, POPULATION) VALUES (6, 'AUSTRALIA', 43111704);
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME, POPULATION) VALUES (7, 'ANTARCTICA', 0);


-- LOAD DATA INTO THE HIGH_TEMPERATURE TABLE
-- DROP THE OLD VERSION OF THE TABLE (IF ONE EXISTS)
DROP TABLE IF EXISTS HIGH_TEMPERATURE;

CREATE TABLE HIGH_TEMPERATURE
(
    CITY              VARCHAR(50),
    YEAR              INT,
    HIGH_TEMPERATURE  INT,
    CONSTRAINT CHECK (YEAR BETWEEN 1880 AND 2200),
    CONSTRAINT CHECK (HIGH_TEMPERATURE < 200),
    PRIMARY KEY (CITY, YEAR)
);

-- REINSERT THE DATA INTO THE HIGH_TEMPERATURE TABLE
INSERT INTO HIGH_TEMPERATURE (CITY, YEAR, HIGH_TEMPERATURE)
VALUES
('DEATH VALLEY, CA', 		2020,	130),
('INTERNATIONAL FALLS, MN', 2020,	78),
('NEW YORK, NY', 			2020,	96),
('DEATH VALLEY, CA', 		2021,	128),
('INTERNATIONAL FALLS, MN', 2021,	77),
('NEW YORK, NY', 			2021,	98);


CREATE DATABASE FEEDBACK;
USE FEEDBACK;

CREATE TABLE CUSTOMER
(
    CUSTOMER_ID     INT,
    FIRST_NAME	    VARCHAR(50),
    LAST_NAME       VARCHAR(50),
    ADDRESS         VARCHAR(100),
    PRIMARY KEY (CUSTOMER_ID)
); 

-- IF YOU WANT TO LOAD THE CUSTOMER TABLE WITH DATA, RUN THESE COMMANDS:
INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ADDRESS)
VALUES
(1, 'BOB', 'SMITH', '12 DREARY LANE'),
(2, 'SALLY', 'JONES', '76 BOULEVARD MEUGLER'),
(3, 'KAREN', 'BELLYACHER', '354 MAIN STREET');

CREATE TABLE COMPLAINT
    (
    COMPLAINT_ID  INT,
    CUSTOMER_ID   INT,
    COMPLAINT     VARCHAR(200),
    PRIMARY KEY (COMPLAINT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
    );
	
-- INSERT ONE ROW OF DATA INTO THE COMPLAINT TABLE
INSERT INTO COMPLAINT (COMPLAINT_ID, CUSTOMER_ID, COMPLAINT)
VALUES (1, 3, 'I WANT TO SPEAK TO YOUR MANAGER');

-- TRYING TO INSERT THIS ROW INTO THE COMPLAINT TABLE WILL FAIL
-- BECAUSE THERE IS NO CUSTOMER 4 IN THE CUSTOMER TABLE.
INSERT INTO COMPLAINT (COMPLAINT_ID, CUSTOMER_ID, COMPLAINT)
VALUES (2, 4, 'MY FOOD WAS COLD');

ALTER TABLE CUSTOMER ADD COLUMN ZIP VARCHAR(50);
ALTER TABLE CUSTOMER DROP COLUMN ADDRESS;
ALTER TABLE CUSTOMER RENAME COLUMN ZIP TO ZIP_CODE;
ALTER TABLE CUSTOMER RENAME TO VALUED_CUSTOMER;

CREATE TABLE CONTACT
(
    CONTACT_ID     INT,
    NAME           VARCHAR(50)  NOT NULL,
    CITY           VARCHAR(50),
    PHONE          VARCHAR(20),
    EMAIL_ADDRESS  VARCHAR(50)  UNIQUE,
    PRIMARY KEY(CONTACT_ID)
);

-- NOTE THAT FOR CONTACT 3, NULL DOES NOT HAVE QUOTES AROUND IT:
INSERT INTO CONTACT VALUES
(1, 'STEVE CHEN',	'BEIJING',	'123-3123',	'STEVE@SCHEN21.ORG'),
(2, 'JOAN FIELD',	'NEW YORK',	'321-4321',	'JFIELD@JFNY99.COM'),
(3, 'BILL BASHFUL',	'LINCOLN',	NULL,		'BB@SHYGUY77.EDU');

CREATE TABLE JOB
(
    JOB_ID     INT,
    JOB_DESC   VARCHAR(100),
    SHIFT      VARCHAR(50) DEFAULT '9-5',
    PRIMARY KEY (JOB_ID)
);


CREATE TABLE PRODUCT
	(
	PRODUCT_ID		INT,
	PRODUCT_NAME	VARCHAR(100),
	SUPPLIER_ID		INT
	);
	
-- CREATE AN INDEX ON THE SUPPLIER_ID COLUMN TO SPEED UP RETRIEVAL
CREATE INDEX PRODUCT_SUPPLIER_INDEX ON PRODUCT(SUPPLIER_ID);

DROP TABLE PRODUCT;

CREATE DATABASE PET;

-- DON'T FORGET TO RUN THE USE COMMAND SO THAT THE TABLES BELOW WILL BE 
-- CREATED IN THE "PET" DATABASE
USE PET;

-- DROP ANY OLD VERSIONS OF THIS TABLE BEFORE RECREATING IT.
DROP TABLE IF EXISTS OWNER;
CREATE TABLE OWNER
(
	OWNER_ID		INT,
	OWNER_NAME		VARCHAR(100),
	OWNER_ADDRESS	VARCHAR(100),
	PRIMARY KEY (OWNER_ID)
);

DROP TABLE IF EXISTS BREED;

CREATE TABLE BREED
(
	BREED_ID	INT,
	BREED_NAME	VARCHAR(50),
	TEMPERAMENT	VARCHAR(100),
	PRIMARY KEY (BREED_ID)
);
	
DROP TABLE IF EXISTS VETERINARIAN;
CREATE TABLE VETERINARIAN
(
	VETERINARIAN_ID			INT,
	VETERINARIAN_NAME		VARCHAR(100),
	VETERINARIAN_ADDRESS	VARCHAR(100),
	VETERINARIAN_PHONE		VARCHAR(100),
	PRIMARY KEY (VETERINARIAN_ID)
);

DROP TABLE IF EXISTS DOG;

CREATE TABLE DOG
(
    DOG_ID            INT,
    DOG_NAME          VARCHAR(50) UNIQUE,
    OWNER_ID          INT,
    BREED_ID          INT,
    VETERINARIAN_ID   INT,
    PRIMARY KEY (DOG_ID),
    FOREIGN KEY (OWNER_ID) REFERENCES OWNER(OWNER_ID),
    FOREIGN KEY (BREED_ID) REFERENCES BREED(BREED_ID),
    FOREIGN KEY (VETERINARIAN_ID) REFERENCES VETERINARIAN(VETERINARIAN_ID)
);

SHOW INDEXES FROM DOG;



####CHAPTER 3 PRACTICE####
#SELECT COMMAND PRACTICE###
USE LAND;
SELECT CONTINENT_ID,
CONTINENT_NAME,
POPULATION
FROM CONTINENT WHERE CONTINENT_NAME='ASIA';

SELECT POPULATION 
FROM CONTINENT
WHERE CONTINENT_NAME='ASIA';


#TRY IT YOURSELF CHAPTER 3###

USE FEEDBACK;
SELECT FIRST_NAME,
LAST_NAME
FROM CUSTOMER
WHERE FIRST_NAME='KAREN';
######


USE LAND;
SELECT * FROM CONTINENT;


